import { MigrationInterface, QueryRunner } from 'typeorm'

export class ContentUpdate implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<any> {
    // ----------------- Data -------------------
    // @TODO: make these queries content up to date
    await queryRunner.query(`
        INSERT INTO "privacy_policy" ("id", "json_dump", "timestamp", "lang") VALUES
        (1,	'[{"type":"HEADING", "content":"KEBIJAKAN PRIVASI Period Tracker App"},
        {"type":"CONTENT", "content":"Menjaga informasimu adalah hal penting untuk Period Tracker App. Kami melakukan yang terbaik agar informasi yang kamu masukkan di dalam aplikasi terjaga kerahasiaannya dan sebisa mungkin aman. Informasi yang kamu bagikan tentang siklus menstruasi bersifat pribadi dan kami sangat menghormatinya.\n\nSaat kamu memasukkan informasi di aplikasi, Period Tracker App menggunakan teknologi yang mengubah ‘data’ menjadi informasi yang berguna yang dapat membantu kamu untuk belajar lebih banyak tentang pola siklus menstruasimu, untuk membantu kamu mengambil control atas tubuh dan kesehatanmu: contohnya, dengan memberikanmu informasi tentang bagaimana mengatur menstruasi atau rasa sakit.\n\n Kami bertujuan untuk memiliki standar tertinggi terkait privasi dan keamanan dan kami sangat berkomitmen untuk menjadi transparan tentang bagaimana kami memproses dan menggunakan data."},
        {"type":"CONTENT", "content":"Kebijakan Privasi ini menjelaskan tentang apa yang terjadi pada data yang kamu masukkan ketika kamu melacak menstruasimu: bagaimana informasimu dikumpulkan, disimpan dan digunakan, dan langkah-langkah apa saja yang kami ambil untuk memastikan bahwa data kamu tetap aman.\n\nSilahkan baca Kebijakan Privasi kami dengan seksama sebelum menggunakan Period Tracker App dan cek kembali secara rutin untuk mengecek pembaruan. Mohon diingat, dengan mengakses dan menggunakan aplikasi atau situs web, kamu setuju dengan Kebijakan Privasi ini. \n\nPeriod Tracker App dibuat oleh Organization. Mohon jangan ragu untuk menghubungi kami jika kamu memiliki pertanyaan tentang penggunaan data di Period Tracker App. Ini adalah formulir kontak di website Period Tracker App."},
        {"type":"HEADING", "content":"1. Informasi apakah yang dikumpulkan oleh Period Tracker App tentang kamu?"},
        {"type":"CONTENT", "content":"Untuk tujuan dari Kebijakan Privasi ini, “Informasi Personal” berarti informasi apapun yang memungkinkan kami untuk mengidentifikasi seorang individu, secara langsung maupun tidak langsung, dengan merujuk pada pengidentifikasi seperti nama, nomor identitas, lokasi data, pengenal online atau satu atau lebih banyak faktor yang spesifik kepada individu.  \n\nDijelaskan di bawah ini adalah tujuan kami mengumpulkan dan memproses informasi personal dan sumber serta tipe data yang diproses untuk tujuan-tujuan ini:"},
        {"type":"HEADING", "content":"1.1 Untuk memberikanmu layanan kami dan untuk mempelajari kebutuhanmu."},
        {"type":"HEADING", "content":"Informasi masuk"},
        {"type":"CONTENT", "content":"Agar aplikasi alat pelacak menstruasi berfungsi, kamu perlu membuat sebuah tanda masuk. Dalam pembuatan tanda masuk, kami meminta kamu untuk memberikan tampilan atau nama pengguna, tanggal lahir, jenis kelamin dan lokasi. Kami mendorong kamu untuk memilih nama tampilan yang tidak menunjukkan nama asli atau informasi lain yang bisa digunakan untuk mengidentifikasi kamu - terutama jika kamu di bawah usia 18 tahun."},
        {"type":"HEADING", "content":"Data perangkat"},
        {"type":"CONTENT", "content":"Di dalam aplikasi, kami mengumpulkan informasi melalui alat yang kamu gunakan untuk mengakses layanan Period Tracker App, seperti model, sistem operasi, bahasa, lokasi, dan durasi sesi."},
        {"type":"CONTENT", "content":"Informasi personal yang kami kumpulkan secara otomatis dari penggunaan kamu di aplikasi dan situs web. Ketika kamu menggunakan aplikasi, kami dan pemberi layanan pihak ketiga memproses data tentang bagaimana kamu berinteraksi dengan aplikasi. Kami menggunakan aplikasi pusat dan beberapa fitur pelacak yang dimodifikasi untuk merekam interaksi ini."},
        {"type":"CONTENT", "content":"Kami melakukan ini untuk memahami penggunaan layanan kami, misalnya fungsi apa dari aplikasi yang kamu gunakan untuk memastikan semua fitur yang diberikan oleh aplikasi berfungsi dengan baik. Kami mengumpulkan informasi ini untuk mengerti fitur mana yang paling berguna untuk semua pengguna dan untuk berkomunikasi denganmu tentang aplikasi dan layanannya. Contohnya, kami saat ini sedang melacak apakah pengguna sedang memodifikasi waktu mulai menstruasinya, karena informasi ini sangat berguna terkait dengan keakuratan prediksi."},
        {"type":"CONTENT", "content":"Kami juga melakukan ini untuk memungkinkan kami mengirimkan pengingat di ponsel pintar melalui pesan dalam aplikasi dan notifikasi yang ditekan. Kamu bisa mengubah bagaimana kamu menerima notifkasi di aplikasi dan perangkatmu kapanpun dengan cara pergi ke bagian Pengaturan."},
        {"type":"CONTENT", "content":"Kami juga melakukan ini untuk memungkinkan kami mengirimkan pengingat di ponsel pintar melalui pesan dalam aplikasi dan notifikasi yang ditekan. Kamu bisa mengubah bagaimana kamu menerima notifkasi di aplikasi dan perangkatmu kapanpun dengan cara pergi ke bagian Pengaturan. Kesimpulannya, kami memproses data untuk memberikan kamu layanan yang terbaik yang bisa kamu dapatkan melalui Period Tracker App."},
        {"type":"CONTENT", "content":"Kami tidak memproses data personal yang bisa mengenali diri kamu (seperti nama depan, nama belakang, email) atau data terkait kesehatan."},
        {"type":"CONTENT", "content":"Kami juga menggunakan Google Analytics untuk melacak interaksi pengguna dengan website. Dengan cara ini, kami bisa mengakses halaman apa yang paling sering dilihat, durasi kunjungan, dll. Informasi personal yang kami kumpulkan secara otomatis dari penggunaanmu pada aplikasi dan situs web."},
        {"type":"HEADING", "content":"Bagaimana informasi ini dikumpulkan"},
        {"type":"CONTENT", "content":"Di situs web kami, kami menggunakan cookie, yang merupakan file teks kecil yang mengidentifikasi komputer, telepon, dan perangkat lainmu ke server kami. Dengan menggunakan situs web, kamu menyetujui penempatan cookie dan teknologi serupa di browser kamu sesuai dengan Kebijakan Privasi ini. Informasi ini dikumpulkan melalui situs web termasuk alamat IP kamu, lokasi jaringan, browser apa yang kamu gunakan, ID perangkat dan karakteristik, versi sistem operasi, preferensi bahasa, URL rujukan, dan informasi tentang penggunaan situs web kami."},
        {"type":"CONTENT", "content":"Kami juga bekerja dengan Google Analytics, yang menggunakan cookie atau teknologi serupa untuk mengumpulkan dan menganalisa informasi tentang penggunaan situs web dan laporan pada aktivitas dan tren. Kamu bisa belajar lebih banyak tentang praktik Google dengan membuka https://www.google.com/policies/privacy/partners/."},
        {"type":"CONTENT", "content":"Jika kamu tidak mau informasi dikumpulkan melalui penggunaan cookie, sebagian besar browser memungkinkan kamu untuk secara otomatis menolak cookie atau memberikan pilihan untuk menolak atau menerima transfer cookie atau beberapa jenis cookie dari situs web tertentu ke komputermu. Kamu mungkin ingin membaca lebih jauh di http://www.allaboutcookies.org/manage-cookies/index.html untuk mengetahui lebih lanjut tentang cookie. \n Jika kamu tidak menerima layanan cookie kami, kamu mungkin akan mengalami beberapa ketidaknyamanan dalam menggunakan situs web kami."},
        {"type":"HEADING", "content":"1.2 Untuk memberikanmu pandangan personal tentang menstruasi dan kesehatanmu"},
        {"type":"CONTENT", "content":"Informasi yang kami lacak menggunakan Period Tracker App tentang kesehatan dan aktivitasmu tergolong data personal yang sensitif. Untuk aplikasi Period Tracker App, kebanyakan data dikumpulkan, menggunakan interaksi pengguna dengan mesin prediksi. Nama, bahasa, tema dan jawaban pada kartu harian dan kuis pengguna akan disimpan, dan ini direkam jika pengguna memodifikasi prediksi menstruasi, membuatnya lebih pendek, memodifikasi prediksi saat ini, dll."},
        {"type":"CONTENT", "content":"Jika pengguna menghapus akun mereka, semua data akan dihapus dari server."},
        {"type":"HEADING", "content":"Data kesehatan dan sensitif"},
        {"type":"CONTENT", "content":"Data kesehatan, seperti data menstruasimu yang sudah lewat dan saat ini, dan mood, tubuh atau aktivitas yang kamu lacak melalui aplikasi (cth. rasa sakit, kembung, olahraga, tidur, dan aliran menstruasi) dikumpulkan dan digunakan untuk memberikan layanan untuk kamu - seperti memprediksi tanggal menstruasi yang akan datang atau memberikanmu pengingat atau notifikasi terkait menstruasi dan kesehatan."},
        {"type":"CONTENT", "content":"Teknologi yang digunakan untuk memprediksi oleh Period Tracker App memproses data ini dan memberikanmu informasi. Namun, jika informasi personalmu tentang ini tidak dibagikan kepada pihak manapun. Period Tracker App memberikan pertanyaan-pertanyaan di aplikasi untuk meminta masukkan kamu tentang aplikasi, seperti kinerja aplikasi atau kegunaan dari informasi yang Period Tracker App berikan dan pengalamanmu menggunakan aplikasi. Informasi yang kamu berikan melalui jawaban survei dan pertanyaan diproses oleh Period Tracker App dengan tujuan yang sudah disebutkan pada Kebijakan Privasi ini."},
        {"type":"CONTENT", "content":"Informasi yang kamu masukkan pada bagian Catatan akan tetap bersifat rahasia: informasi ini tidak akan dikumpulkan, diakses atau digunakan oleh aplikasi dengan cara apapun."},
        {"type":"HEADING", "content":"Kumpulan data"},
        {"type":"CONTENT", "content":"Kami mungkin mengidentifikasi dan mengumpulkan informasi melalui aplikasi untuk analisa statistik dan tujuan sah lainnya, termasuk dalam studi penelitian yang ditujukan untuk meningkatkan pemahaman kami atas penggunaan teknologi dan alat digital oleh orang muda. Hasil dari penelitian ini akan kami bagikan kepada pihak ketiga, seperti mitra, pendukung, pendidik, dan peneliti kami melalui konferensi, jurnal ilmilah, dan publikasi lainnya. Jika kami melakukan ini, semua data akan dikumpulkan dan tidak satupun dari data kamu bisa digunakan untuk mengidentifikasi diri kamu: kami tidak akan memproses data personal yang mengidentifikasi kamu sebagai individu (seperti nama depan, nama belakang, email) atau data terkait kesehatan."},
        {"type":"CONTENT", "content":"Beberapa informasi yang mungkin berguna bagi informasi personal dan privasi:"},
        {"type":"CONTENT", "content":"i. Kami mungkin menggunakan Data Personal untuk mendorong Ketentuan Penggunaan kami, membela hak-hak hukum kami, dan untuk mematuhi kewajiban hukum dan kebijakan internal kami.\n\n ii. Period Tracker App sudah dirancang untuk meminimalkan penggunaan data personal kamu. Kami hanya mengumpulkan dan memproses datamu untuk tujuan yang sudah disebutkan di atas.\n\n iii. Keamanan server kami dicek secara rutin oleh ahli untuk memastikan data kamu dilindungi dari akses yang tidak sah. Kamu bisa menghubungi kami jika memiliki pertanyaan terkait keamanan layanan kami, ini adalah formulir kontak pada situs web Period Tracker App [insert URL].\n\n iv. Kami tidak menyimpan data kamu dalam format yang dapat diidentifikasi lebih lama dari yang diperlukan untuk memberikan layanan kami.\n\n  v. Sebagai pengguna Period Tracker App, kamu mungkin bisa menggunakan hak pengguna kamu untuk meminta informasi tentang data personal yang diproses oleh Period Tracker App. Permintaan kamu akan dikirimkan secara elektronik."},
        {"type":"HEADING", "content":"2. Keamanan Data"},
        {"type":"CONTENT", "content":"Kami menggunakan banyak langkah wajar - fisik dan elektronik - untuk mencegah akses tidak sah dan bocoran kepada Informasi Personal kamu. Namun, selalu ada kemungkinan bahwa pihak ketiga secara tidak sah mencegat atau mengakses Informasi Pribadi kamu atau komunikasi pribadi. Jadi, meskipun kami bekerja sangat keras untuk melindungi Informasi personal kamu, kami tidak menjamin bahwa informasi atau komunikasimu akan tetap rahasia."},
        {"type":"HEADING", "content":"Saran untuk melindungi datamu"},
        {"type":"CONTENT", "content":"Kami percaya bahwa ancaman terbesar pada keamanan dan privasi datamu adalah jika seseorang - mungkin orang yang kamu kenal - memiliki akses ke perangkatmu. Data yang kamu masukkan di Period Tracker App adalah rahasia dan sebaiknya tetap seperti itu. Kami telah memberikan beberapa cara untuk menjaga keamanan perangkat kamu di bawah ini:"},
        {"type":"CONTENT", "content":"i. Mengaktifkan PIN atau kata kunci yang unik untuk membuat tanda masuk. Buatlah kata kunci yang personal dan tidak mudah bagi orang untuk menebaknya. Contohnya, jangan gunakan tanggal lahir atau namamu. Jika kamu berbagi penggunaan ponsel dengan orang lain, mengaktifkan PIK atau kata kunci yang uni akan membantu memastikan bahwa hanya kamu yang bisa mengakses data di Period Tracker App."},
        {"type":"CONTENT", "content":"ii. Siapkan fitur yang bisa membuat kamu menghapus semua data dari ponselmu jika kamu ponselmu hilang atau dicuri."},
        {"type":"CONTENT", "content":"Untuk Android, unduh atau atur Find My Device (sebelumnya Android Device Manager) dari Google play Store dan jika dibutuhkan, hubungkan dengan situs web untuk mengunci atau menghapus data ponselmu dari jarak jauh."},
        {"type":"HEADING", "content":"3. Situs web pihak ketiga"},
        {"type":"CONTENT", "content":"Aplikasi kami atau situs web kami mungkin berisi tautan ke situs web lain yang tidak dilindungi oleh Kebijakan Privasi ini. Kebijakan Privasi ini hanya berlaku untuk proses Informasi Personal oleh Period Tracker App. Itu tidak membahas, dan kami tidak bertanggung jawab untuk, privasi, informasi atau praktik pihak ketiga manapun, yang mengoperasikan situs atau layanan apapun yang ditautkan oleh situs web atau aplikasi tersebut.\n\n,\n  Dimasukkannya sebuah tautan pada situs web atau aplikasi tidak berarti dukungan kepada layanan atau situs yang ditautkan oleh Organization. Mohon diketahui bahwa ketentuan Kebijakan Privasi ini tidak berlaku untuk situs web atau konten luar, atau untuk mengumpulkan data setelah kamu mengklik situs tautan tersebut."},
        {"type":"HEADING", "content":"4. Pemberitahuan perubahan pada Kebijakan Privasi"},
        {"type":"CONTENT", "content":"Kami meninjau langkah-langkah keamanan dan Kebijakan Privasi kami dan kami mungkin mengubah kebijakan kami karena kami anggap sesuai. Jika kami membuat perubahan terhadap praktik privasi, kami akan memberitahu melalui website atau aplikasi yang memberitahukan bahwa Kebijakan Privasi sudah diperbarui. Perubahan tersebut akan langsung efektif segera setelah kami memasukkannya ke aplikasi atau situs web kami. Untuk alasan ini, kami mendorong kamu untuk mengecek Kebijakan Privasi kami secara rutin. \n Tanggal “Terakhir Diperbarui” terdapat di akhir halaman ini menunjukkan kapan Kebijakan Privasi ini terakhir diperbarui. Jika kamu terus menggunakan aplikasi atau website setelah adanya perubahan ini, berarti kamu menyetujui revisi Kebijakan Privasi."},
        {"type":"CONTENT", "content":"Silahkan menghubungi kami jika kamu memerlukan lebih banyak informasi tentang Kebijakan Privasi. Ini adalah formulir kontak Period Tracker App pada situs web: [insert URL].\n\nTerakhir diperbarui: 17 Juli 2019"}]',	'2020-10-13 16:46:57.259',	'id'); 
    `)
    await queryRunner.query(`
        INSERT INTO "about" ("id", "json_dump", "timestamp", "lang") VALUES
        (1,	'[{"type":"CONTENT", "content":"Period Tracker App adalah aplikasi ponsel yang membantu remaja perempuan untuk mengontrol tubuh dan hidup mereka. Merasa lebih percaya diri dengan melacak menstruasimu serta mendapatkan fakta-fakta yang perlu diketahui seputar menstruasi."},
        {"type":"HEADING", "content":"Apa itu Period Tracker App?"},
        {"type":"CONTENT", "content":"Period Tracker App adalah alat pelacak menstruasi yang didesain untuk remaja perempuan oleh remaja perempuan: ini menyenangkan dan positif karena kami ingin mengubah rasa malu dan perasaan tidak nyaman saat menstruasi menjadi lebih menyenangkan!"},
        {"type":"HEADING", "content":"Kenapa Organization membuat Period Tracker App?"},
        {"type":"CONTENT", "content":"Organization membuat Period Tracker App sebagai bagian dari misi mereka untuk mempromosikan pendidikan dan kesehatan remaja perempuan dengan mengubah salah satu tabu paling besar di dunia, yaitu: menstruasi."},
        {"type":"CONTENT", "content":"Semua perempuan mengalami menstruasi. Ini adalah hal yang alami tapi remaja perempuan masih merasa malu karenanya. Mereka jarang mendapatkan informasi tentang apa yang terjadi pada tubuh mereka pada saat terjadi banyak perubahan di dalam tubuh mereka."},
        {"type":"CONTENT", "content":"Hal yang sulit untuk mendapatkan informasi yang bisa dipercaya dan relevan secara online. Banyak sekali mitos-mitos di luar sana. Semua hal ini bisa membuat menstruasi menjadi sumber stres. Period Tracker App didesain untuk membuat remaja perempuan mengatur menstruasinya dengan rasa percaya diri karena remaja perempuan seharusnya bisa membuat keputusan yang bertanggung jawab terkait dengan tubuh dan hidup mereka."},
        {"type":"HEADING", "content":"Bagaimana Organization membuat Period Tracker App?"},
        {"type":"CONTENT", "content":"Kami menghabiskan waktu berbulan-bulan untuk berdiskusi dengan lebih dari 400 remaja di Mongolia dan Indonesia tentang menstruasi, ketakutan, harapan dan hidup mereka kemudian bekerja bersama untuk membuat Period Tracker App! Kami juga bekerja dengan ahli pendidikan dan kesehatan untuk memastikan bahwa Period Tracker App merefleksikan prinsip, standar tinggi kesehatan dan panduan Organization."},
        {"type":"HEADING", "content":"Bagaimana cara kerja Period Tracker App?"},
        {"type":"CONTENT", "content":"Period Tracker App membiarkan kamu memasukkan informasi tentang menstruasi, tubuh, aktivitas dan mood kamu, kemudian berdasarkan informasi yang kamu masukkan, Period Tracker App memberikan tebakan menstruasi yang akan datang dan siklus ovulasi. Terdapat calendar yang berfungsi sebagai buku harian dan membantu kamu untuk mengingat. Period Tracker App memberikan tips-tips dan motivasi lewat permainan dan kuis juga!"},
        {"type":"HEADING", "content":"Apa yang membuat Period Tracker App berbeda?"},
        {"type":"CONTENT", "content":"Period Tracker App berbeda dari aplikasi pelacak menstruasi lainnya karena aplikasi ini dibuat untuk remaja perempuan. Period Tracker App bukanlah sebuah bisnis, tapi ini adalah sebuah layanan bagi remaja perempuan yang mengikutsertakan semua dan tidak menghakimi, dan menjaga standar paling tinggi tentang privasi dan perlindungan data."},
        {"type":"CONTENT", "content":"Period Tracker App dibuat dengan cara terbuka sehingga orang lain dapat belajar dari proses tentang bagaimana membuat sebuah layanan kesehatan masyarakat digital. Dengan cara ini, diharapkan lebih banyak orang berkontribusi untuk mengubah cara informasi digital digunakan dari mengutamakan profit menjadi lebih mengutamakan kepentingan publik."}]',	'2020-10-13 16:46:57.259',	'id'); 
    `)
    await queryRunner.query(`
        INSERT INTO "terms_and_conditions" ("id", "json_dump", "timestamp", "lang") VALUES
        (1,	'[{"type":"HEADING", "content":"S & K Period Tracker App"},
        {"type":"HEADING", "content":"DENGAN MENGGUNAKAN Period Tracker App, KAMU SETUJU DENGAN SYARAT-SYARAT INI. Jika kamu tidak setuju dengan persyaratan ini, kamu sebaiknya tidak menggunakan Period Tracker App."},
        {"type":"HEADING", "content":"ISI"},
        {"type":"CONTENT", "content":"Period Tracker App adalah cara untuk memonitor dan belajar tentang siklus menstruasi juga memberikan informasi tentang menstruasimu serta kesehatan perempuan. Layanan ini diberikan secara gratis.JIKA ADA MASALAH KESEHATAN PRIBADI, BERKONSULTASILAH DENGAN SEORANG AHLI KESEHATAN."},
        {"type":"CONTENT", "content":"Period Tracker App tidak dibuat untuk menggantikan metode kontrasepsi dan/atau memberikan saran medis: ini hanya ditujukan untuk memberikan informasi. Dengan menggunakan Period Tracker App, kamu setuju untuk menggunakannya untuk tujuan yang telah ditentukan dan terutama tidak menggunakannya sebagai alat kontrasepsi dan/atau tujuan medis."},
        {"type":"HEADING", "content":"DATA DAN KEGUNAAN"},
        {"type":"CONTENT", "content":"Period Tracker App memberikan informasi umum tentang kesehatan perempuan, menstruasi, kesuburan dan topik relevan lainnya. Period Tracker App mengumpulkan data yang dimasukkan oleh pengguna terkait dengan siklus menstruasi, aktivitas fisik, tubuh dan kesehatan. \n  Period Tracker App memproses data-data yang berkaitan dengan informasi medis tentang siklus menstruasi (cth. panjangnya siklus menstruasi) dan informasi kesehatan perempuan lainnya. Kombinasi data ini membiarkan aplikasi untuk membuat asosiasi dan mengidentifikasi pola-pola antara kejadian yang terkait dengan siklus menstruasi dan kesehatan perempuan dengan menggunakan rumus matematika/statistik dan perhitungan berdasarkan algoritma."},
        {"type":"CONTENT", "content":"Untuk informasi tentang data yang kami kumpulkan dan gunakan, silahkan baca Kebijakan Privasi kami."},
        {"type":"HEADING", "content":"PEMBARUAN KONTEN"},
        {"type":"CONTENT", "content":"Meskipun Organization membuat upaya-upaya yang wajar untuk memperbarui informasi di aplikasi kami, kami tidak membuat pernyataan, jaminan atau garansi, baik tersurat ataupun tersirat bahwa konten di aplikasi kami itu akurat, lengkap atau terbaru."},
        {"type":"HEADING", "content":"PERUBAHAN SYARAT DAN KETENTUAN"},
        {"type":"CONTENT", "content":"Organization mengubah ketentuan ini dari waktu ke waktu. Setiap kali kamu ingin menggunakan Period Tracker App, silakan periksa ketentuan ini untuk memastikan bahwa kamu memahami persyaratan yang berlaku pada saat itu."},
        {"type":"HEADING", "content":"PERUBAHAN APLIKASI"},
        {"type":"CONTENT", "content":"Organization mungkin memperbaharui dan mengubah Period Tracker App dari waktu ke waktu untuk memberikan informasi terbaru, tautan atau memberikan fungsi baru dan mencerminkan perubahan pada kebutuhan pengguna kami."},
        {"type":"HEADING", "content":"PENANGGUHAN ATAU PEMBATALAN APLIKASI"},
        {"type":"CONTENT", "content":"Period Tracker App tersedia secara gratis. Organization tidak menjamin bahwa Period Tracker App, atau konten apapun di dalamnya akan selalu tersedia atau tidak terputus. Kami dapat menangguhkan atau menarik atau membatasi ketersediaan dari semua bagian di Aplikasi kami untuk alasan operasional atau alasan lainnya. Kami akan berupaya untuk memberikan pemberitahuan yang wajar tentang segala penangguhan atau penarikan."},
        {"type":"HEADING", "content":"MEMBUAT PENGGUNA LAIN MENGETAHUI SYARAT DAN KETENTUAN"},
        {"type":"CONTENT", "content":"Jika ada orang lain yang menggunakan Period Tracker App melalui perangkat ponselmu, kamu juga bertanggung jawab untuk memastikan bahwa mereka mengetahui ketentuan penggunaan, syarat dan ketentuan lainnya dan mereka akan mematuhinya."},
        {"type":"HEADING", "content":"MENJAGA DETAIL AKUN AMAN"},
        {"type":"CONTENT", "content":"Jika kamu memilih, atau kamu diberikan kode indentifikasi pengguna, kata kunci atau informasi lainnya sebagai bagian dari prosedur keamanan Organization, kamu harus menjaga kerahasiaan informasi tersebut. Kamu sebaiknya tidak memberikan informasi ini kepada pihak ketiga."},
        {"type":"CONTENT", "content":"Organization memiliki hak untuk menonaktifkan kode identifikasi atau kata kunci apapun, baik yang dipilih oleh kamu atau dialokasikan oleh kami kapan saja, jika menurut pendapat kami secara wajar bahwa kamu telah gagal untuk mematuhi ketentuan dan syarat penggunaan."},
        {"type":"HEADING", "content":"LOKASI KAMU"},
        {"type":"CONTENT", "content":"Dengan menggunakan Period Tracker App, Anda setuju bahwa lokasi yang Anda berikan saat mendaftar akurat."},
        {"type":"HEADING", "content":"TAUTAN LUAR DAN SUMBER LAINNYA"},
        {"type":"CONTENT", "content":"Period Tracker App mungkin memberikan tautan kepada website dan sumber lain yang diluar control Organization. Dimasukkannya tautan sumber lain tidak berarti ini menunjukkan dukungan atau persetujuan Organization terhadap website, produk atau layanan apapun di dalamnya."},
        {"type":"CONTENT", "content":"Organization tidak bertanggung jawab atau memikul kewajiban apapun terkait dengan website tersebut, termasuk misalnya tanggung jawab atau keakuratan tentang informasi yang diberikan, data, pendapat atau pernyataan yang dibuat di website tersebut."},
        {"type":"CONTENT", "content":"Semua yang ada di dalam situs ini adalah untuk kamu dan teman sebayamu, bukan untuk digunakan secara komersil."},
        {"type":"HEADING", "content":"KERUGIAN ATAU KERUSAKAN"},
        {"type":"CONTENT", "content":"Kami tidak mengecualikan atau membatasi dengan cara apapun terkait tanggung jawab kami kepadamu dimana itu akan menjadi sebuah hal yang melanggar hukum. Hal ini termasuk tanggung jawab atas kematian atau cedera pribadi yang disebabkan oleh kelalaian kami atau karyawan, agen, atau sub-kontraktor kami dan untuk penipuan dan kesalahan penerjemahan."},
        {"type":"CONTENT", "content":"Harap dipahami bahwa kami hanya menyediakan aplikasi untuk penggunaan personal, domestik dan pribadi. Kamu setuju untuk tidak menggunakan aplikasi kami untuk tujuan komersil atau bisnis, dan kami tidak bertanggung jawab atas kerugian materi, kehilangan bisnis, gangguan bisnis atau kehilangan kesempatan bisnis."},
        {"type":"HEADING", "content":"INFORMASI PERSONAL KAMU"},
        {"type":"CONTENT", "content":"Kami hanya akan menggunakan informasi personal kamu sesuai yang tertera di dalam Kebijakan Privasi kami."},
        {"type":"HEADING", "content":"SENGKETA"},
        {"type":"CONTENT", "content":"Ketentuan pengguna, materi pelajaran dan formasinya diatur oleh hukum Amerika Serikat. Pengadilan Amerika Serikat akan memiliki yurisdiksi eksklusif."},
        {"type":"HEADING", "content":"Organization nama dan logo"},
        {"type":"CONTENT", "content":"Nama dan logo Organization merupakan milik Organization secara eksklusif. Mereka dilindungi berdasarkan hukum internasional. Penggunaan tanpa ijin dilarang. Nama dan lambang sebaiknya tidak dicontoh atau direproduksi pada cara apapun tanpa ijin tertulis dari Organization. Jika kamu memiliki pertanyaan tentang hal ini, silahkan hubungi Organization."}]',	'2020-10-13 16:46:57.259',	'id'); 
    `)
  }
  async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`
        DROP TABLE IF EXISTS "terms_and_conditions";
        DROP SEQUENCE IF EXISTS terms_and_conditions_id_seq;
    `)
    await queryRunner.query(`
        DROP TABLE IF EXISTS "about";
        DROP SEQUENCE IF EXISTS about_id_seq;
    `)
    await queryRunner.query(`
        DROP TABLE IF EXISTS "privacy_policy";
        DROP SEQUENCE IF EXISTS privacy_policy_id_seq;   
    `)
  }
}
